server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test  # ← заменили 'postgres' на 'localhost'
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    enable:
      all: false
  prometheus:
    metrics:
      export:
        enabled: false

logging:
  level:
    root: INFO
    org.springframework: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

  # убрали file logging и logstash
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"


#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/cleanup_db
#    username: postgres
#    password: itsme
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  jackson:
#    serialization:
#      indent_output: true
#
#  data:
#    redis:
#      host: redis
#      port: 6379
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#    enable:
#      all: true
#
#logging:
#  level:
#    root: INFO
#    org.springframework: info
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#
#  file:
#    name: /logs/app.log   # лог будет писаться сюда (и виден logstash'у)
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
